### ISSUE TITLE
Orbax import breaks logging. Again.

### ISSUE THREAD

**Issue by qGentry** [google/orbax#1248]
Basically the same issue I've submitted a while ago here 
https://github.com/google/orbax/issues/699
Even the same repro works :)
Tested on orbax 0.7.0, while 0.5.3 (where fix for this issue was implemented) doesn't break logging 

Maybe it is possible to add some tests for this specific case?

**Comment by qGentry** [comment]
@niketkumar cc

**Comment by qGentry** [comment]
Looks like issue is this log as initialization of ArrayHandler happens on orbax impot:
https://github.com/google/orbax/blob/main/checkpoint/orbax/checkpoint/type_handlers.py#L1117
Commenting it our fixes the issue.

**Comment by niketkumar** [comment]
Thanks for sharing this issue! We are looking into it.

**Comment by niketkumar** [comment]
@qGentry Clarifying your use case:

1. INFO logs in your module are ignored (while your module is loaded/imported).
2. But you expect upstream libraries to not log anything in their modules (import time calls) or set logging defaults.

My test run with logging calls in functions and methods (not module level) ran successfully without skipping INFO logs. 

So the issue seems to be isolated to module level logging only. Is my understanding correct?

**Comment by minotru** [comment]
Hi @niketkumar ,

The issue here comes from usage of module-level import-time `logging.info`, as it implicitly calls `logging.basicConfig`. Then, if users configure logging via `logging.basicConfig` themselves without `force=True`, their logging configuration is silently not applied.

**Comment by niketkumar** [comment]
Even though logging in module (applied during module import) is not a good practice, some upstream module on which Orbax depends has started to do it. It is not in the scope of Orbax.

Please use `logging.basicConfig(..., force=True,...)` to override as per your need.
