### ISSUE TITLE
orbax is unable to save dm-haiku pytrees.

### ISSUE THREAD

**Issue by ethanluoyc** [google/orbax#304]
Hi,

I am experimenting with using orbax for saving checkpoints which consists of dm-haiku state and parameters. However, it seems that the pytree checkpointer is unable to handle "~" characters which are used by inside haiku params/state.

I simple reproducing example is 
```python
from absl import app
import orbax.checkpoint
import jax.numpy as jnp
import pathlib


def main(_):
    ckpt_dir = pathlib.Path("logs")
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    state = {"a/~/foo": jnp.ones((2, 3))} # Changing to "a" works fine.
    ckpt_manager = orbax.checkpoint.CheckpointManager(
        ckpt_dir,
        orbax.checkpoint.PyTreeCheckpointer(),
    )
    print(ckpt_manager.latest_step())
    ckpt_manager.save(0, state)

if __name__ == "__main__":
    app.run(main)

```

**Comment by cpgaffney1** [comment]
The problem is not the '\~' character, but the use of '/'. If you use 'a.~.foo' instead, for example, it works fine. Alternatively, you could do this.
```py
ckpt_manager.save(
      0,
      state,
      save_kwargs={
          "save_args": {"a/~/foo": orbax.checkpoint.SaveArgs(aggregate=True)}
      },
  )
```

The problem is that Orbax tries to create a directory for each parameter saved with Tensorstore, but these directories should be flat, with no further subdirectories for parameter names. If you want a tree with nesting, use this instead.
```py
state = {
  "a": {
    "~": {
      "foo": jnp.ones((2, 3))
    }
  }
}
```

This gives:
```
> ls logs/0/default/
a.~.foo  checkpoint
```

**Comment by ethanluoyc** [comment]
I think for me I would just prefer storing the entire pytree as a single aggregate. I'm not that familiar with Orbax yet. Is there a simple recipe for doing that?

**Comment by cpgaffney1** [comment]
If your parameters are "small" in size (also not sharded, hard requirement) you can use `orbax.checkpoint.SaveArgs(aggregate=True)` as indicated above to put all the parameters in a single msgpack file. 

Otherwise, explore using a new feature provided by Tensorstore, supported in Orbax via `use_ocdbt`. You need to do the following in your training code, and set `use_ocdbt` to True in `PyTreeCheckpointHandler`. Sorry it's not better documented, but it's still an experimental feature at the moment. It does have way better performance though, from the tests we've run.

```
ocdbt_context, coordinator_server = (
        orbax.checkpoint.type_handlers.create_coordinator_server_and_context()
)
orbax.checkpoint.type_handlers.register_standard_handlers_with_options(
        use_ocdbt=True, ts_context=ocdbt_context
)

**Comment by ethanluoyc** [comment]
The aggregate solution works for me.

I did try the ocdbt feature but I think that's for multi-host training? Interesting, without setting up the context but just setting the use_cdbt in the PyTreeCheckpointHandler makes the problem go away.

**Comment by cpgaffney1** [comment]
That's because when use_ocdbt is true, it doesn't need to create directories for each parameter. And the context is only necessary for performance purposes, so you should be fine without it. 

If your parameters are small enough to all be saved into the single msgpack file though, you should go with that approach - it will probably be the most efficeint.
