### ISSUE TITLE
Which weights does each worker load?

### ISSUE THREAD

**Issue by sshleifer** [google/orbax#366]
I wrote a pytorch to orbax checkpoint converter that saves each param to 1 file. I am concerned that each worker will load the full huge model to CPU RAM and die.

I have N questions:
1) Is this the right mental model of what will happen if I try to load this checkpoint with large parallelism?
- every worker pulls every full file from blob, slices the param, takes what it needs.
- If I saved 4 files per param and loaded with 16 way parallelism every worker would still load 1 smaller file and take what it needs.
- If I saved 4 files per param and loaded with 2 way parallelism every worker would load 2 smaller files and concatenate?

2) If my mental model is reasonable it makes sense to improve my converter to save more files per parameter. Is there a way to simulate this parallelism without running the script on N devices? 1 idea that comes to mind is

```
TPU_ACCELERATOR_TYPE='' JAX_PLATFORM='cpu' XLA_FLAGS="--xla_force_host_platform_device_count=1024" python converter.py "$@"
```

on a big CPU machine.

	

### Existing Unsharded Format
 - note these outputs do not include `.zarray` which is present.
 
(produced by converter+orbax)
```
        ├── params.classi.classi_DC.kernel
        │   └── 0.0
        ├── params.layer_stack.decoder.mlp.in_DF.kernel
        │   └── 0.0.0
        ├── params.layer_stack.decoder.mlp.out_FD.kernel
        │   └── 0.0.0
        └── params.token_embedder.embedding_VD
            └── 0.0
```

### Sharded format
(produced by maxtext+orbax)
```
        ├── params.layer_stack.decoder.mlp.in_DF.kernel
        │   ├── 0.0.0
        │   ├── 0.0.1
        │   ├── 0.0.2
        │   └── 0.0.3
        ├── params.layer_stack.decoder.mlp.out_FD.kernel
        │   ├── 0.0.0
        │   ├── 1.0.0
        │   ├── 2.0.0
        │   └── 3.0.0
        ├── params.token_embedder.embedding_VD
        │   ├── 0.0
        │   ├── 1.0
        │   ├── 2.0
        │   └── 3.0

```

**Comment by sshleifer** [comment]
I'm now trying to convert back to pytorch so I need to either (for each param)
(a) run big jax job:
save  `file_{process_index}.np`
save `{process_index: metadata}`  to figure out how to stitch

b) just save metadata and save 
load one/all of these 0.0 tensorstore/zarr files without initializing the mesh/using orbax?
like `tensorstore.load(/'home/ckpt/0.0')`


Do you have a recommendation/code pointer to either one of these approaches?

https://github.com/kingoflolz/mesh-transformer-jax/blob/master/to_hf_weights.py seems like jax checkpoint format 

Thanks for all your help!

**Comment by cpgaffney1** [comment]
Firstly, I'm not familiar with the checkpoint format used by PyTorch, so take my advice with a grain of salt. 

However, if you want to output a PyTorch-format checkpoint using Orbax, it may be possible to implement your own TypeHandler for each relevant type. Right now the default TypeHandlers all use Tensorstore, but you could override with custom logic. Note that all the TypeHandlers save in parallel so this design works best if each parameter is located separately. If you want a limited number of files, you can override AggregateHandler and override that to output a fixed number of files, using `SaveArgs(aggregate=True)` for each parameter. Don't get too attached to this specific setup, as I anticipate that AggregateHandler will go away soon, and TypeHandler will operate on batches of values rather than individual ones.

Not sure if it will be easier for you to just write a converter directly from the checkpoint to PyTorch format, using Tensorstore to load arrays directly, but this is how I would consider doing it with Orbax.

**Comment by sshleifer** [comment]
the pytorch format is basically

`step/process_index/embedding.pt` is a tensor you can load with `torch.load(`step/process_index/embedding.pt`)`

**Comment by cpgaffney1** [comment]
See the JAX [array_serialization](https://github.com/google/jax/blob/main/jax/experimental/array_serialization/serialization.py) library for starters. Orbax TypeHandlers directly call this library. Orbax doesn't have any examples of directly using Tensorstore unfortunately, but that JAX library is pretty straightforward to use. 

For PyTorch, `step/process_index/embedding.pt` implies that there is one file per process and per parameter? If that's the case, then overriding TypeHandler should work if you want to be able to directly save with Orbax.
